{% set name = "anaconda-cloud" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anaconda_cloud-{{ version }}.tar.gz
  sha256: f32735de262aa3d10899b3e945b6f76a12f9f73f02e72d7694416680bee319dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
    - pip
  run:
    - python >=3.8
    - anaconda-cloud-auth
    - anaconda-cli-base
    - anaconda-client >=1.12.2
    - backports

test:
  imports:
    - anaconda_cloud
    - anaconda_cli_base
    - anaconda_cloud_auth
    - binstar_client
  commands:
    - anaconda --version
    - python -c "from anaconda_cloud import __version__; assert __version__ == \"{{ version }}\""

about:
  summary: Anaconda Cloud client tools
  home: https://anaconda.cloud
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - albertdefusco
    - mattkram
